spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.datasource.url=jdbc:mysql://localhost:3306/intro
spring.datasource.username=azura
spring.datasource.password=1234
spring.jpa.hibernate.ddl-auto=validate

spring.jpa.database-platform=org.hibernate.dialect.MySQL8Dialect

# Swagger configuration
springdoc.api-docs.path=/v3/api-docs
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.swagger-ui.enabled=true
springdoc.show-actuator=true
springdoc.cache.disabled=true

# Enable detailed error messages
server.error.include-message=always
server.error.include-stacktrace=always

spring.liquibase.change-log=classpath:db/changelog/db.changelog-master.yaml
spring.liquibase.enabled=true

jwt.secret=AntonAfwefefsfsegwefsgsdgsdf23123124235sedfvsdfs
jwt.expiration=3600000
